export enum EquipPartEnum {
    rightHand = `rightHand`,
    leftHand = `leftHand`,
    twoHand = `twoHand`,
    topCloth = `topCloth`,
    pants = `pants`,
    suit = `suit`,
    head = `head`,
    shoes = `shoes`,
    arm = `arm`,
    glove = `glove`,
    necklace = `necklace`,
    ring = `ring`,
    mask = `mask`,
    eye = `eye`,
    cloak = `cloak`,
    belt = `belt`,
}
