export enum EventEnum {
    Rest = `Rest`,
    infoLabelRefresh = `infoLabelRefresh`,
    SetZoneName = `SetZoneName`,
    setBtnLabel = `setBtnLabel`,
    refreshItemPage = `refreshItemPage`,
    setEuqipText = `setEuqipText`,
    setScrollViewHeightIP = `setScrollViewHeightIP`,
    setScrollViewHeightPM = `setScrollViewHeightPM`,
    init = `init`,
    switchPanelMessageEquip = `switchPanelMessageEquip`,
    switchPanelMessageSozai = `switchPanelMessageSozai`,
    switchPanelMessageUse = `switchPanelMessageUse`,
    equip = `equip`,
}
